[package]
name = "astcenc-rs"
version = "0.1.0"
homepage = "https://github.com/Vurich/astcenc-sys"
repository = "https://github.com/Vurich/astcenc-sys"
documentation = "https://docs.rs/astcenc-sys"
description = "Idiomatic Rust bindings to the official ASTC encoder library from ARM "
license = "Unlicense"
authors = ["Jef <jackefransham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astcenc-sys = { git = "https://github.com/expenses/astcenc-sys" }
bitflags = "1.2"
half = "1.6"
